### ISSUE TITLE
渲染多ofd组件报错，最多只能渲染3个

### ISSUE THREAD

**Issue by nichan-13** [11627685/EasyOFD#7]
代码部分如下：
```
      for (let i = 1; i <= 12; i++) {
        let ofd = new EasyOFD('myofd' + i, this.$refs['ofdViewer' + i]);

        axios
          .get(`http://127.0.0.1:5500/src/assets/test${i}.ofd`, {
            responseType: 'blob',
          })
          .then((response) => {
            const blob = new Blob([response.data], {
              type: 'application/octet-stream',
            });
            ofd.loadFromBlob(blob);
          })
          .catch((error) => {
            console.error('获取文件失败:', error);
          });
      }
```

报错信息：
```
Uncaught TypeError: Cannot read properties of undefined (reading 'appendChild')
    at t.value (easyofd.js:17:61452)
    at new t (easyofd.js:17:61047)
    at Proxy.initOfdViewer (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=script&lang=js:48:19)
    at Proxy.mounted (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=script&lang=js:28:10)
    at eval (runtime-core.esm-bundler.js:2811:88)
    at callWithErrorHandling (runtime-core.esm-bundler.js:296:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:304:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2791:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:461:41)
    at render (runtime-core.esm-bundler.js:6448:5)
```

**Comment by nichan-13** [comment]
封装成组件后使用无异常
```
<useOfd v-for="i in 16" :key="i" :ofdId="'ofd' + i" />
```
